### PR TITLE
Feat : Authentication Page

### PR DESCRIPTION
**Pull request by anuj-kumary**
Created Authentication Page For E-commerce WebApp
- Login Page
- Signup Page
- Auth CSS

Screenshot Of Signup Page -
Screenshot from 2022-02-09 19-30-25

Screenshot Of Login Page -
Screenshot from 2022-02-09 19-30-28

### CODE REVIEW

**Review by hrishi82 — APPROVED** [review]
Looks good to merge

**Review by Rohanmond — APPROVED** [review]
looks good to merge!

**Comment by Shah-Arsalan** [comment]
You can use authentication for password

**Review by Shah-Arsalan — APPROVED** [review]

**Comment by ddivyansh18** [comment]
Looks good to merge !

**Review by ddivyansh18 — APPROVED** [review]

**Pull request merged**
